# Generated by Django 4.2.16 on 2026-04-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planificación'), ('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('archived', 'Archivado')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('os_name', models.CharField(blank=True, max_length=200)),
                ('os_family', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS'), ('network', 'Network Device'), ('embedded', 'Embedded'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('os_accuracy', models.IntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
                ('open_ports', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='core.engagement')),
            ],
            options={
                'ordering': ['-risk_score', 'ip_address'],
                'unique_together': {('engagement', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=3)),
                ('state', models.CharField(choices=[('open', 'Open'), ('filtered', 'Filtered'), ('closed', 'Closed')], default='open', max_length=10)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=200)),
                ('banner', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('cpe', models.CharField(blank=True, max_length=300)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.host')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('host', 'number', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('discovery', 'Host Discovery'), ('port', 'Port Scan'), ('service', 'Service Detection'), ('vuln', 'Vulnerability Scan'), ('ssl', 'SSL/TLS Audit'), ('smb', 'SMB Audit'), ('ad', 'Active Directory'), ('brute', 'Credential Brute Force'), ('snmp', 'SNMP Audit'), ('full', 'Full Audit')], max_length=20)),
                ('targets', models.JSONField(default=list)),
                ('config', models.JSONField(default=dict)),
                ('status', models.IntegerField(choices=[(-1, 'Queued'), (1, 'Running'), (2, 'Completed'), (0, 'Failed'), (3, 'Cancelled')], default=-1)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('hosts_found', models.IntegerField(default=0)),
                ('ports_found', models.IntegerField(default=0)),
                ('vulns_found', models.IntegerField(default=0)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='core.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scan_types', models.JSONField(default=list)),
                ('config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('mitigated', 'Mitigated'), ('accepted', 'Risk Accepted')], default='open', max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cve_id', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('template_id', models.CharField(blank=True, max_length=100)),
                ('ai_analysis', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='core.host')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='core.port')),
            ],
            options={
                'ordering': [models.Case(models.When(severity='critical', then=0), models.When(severity='high', then=1), models.When(severity='medium', then=2), models.When(severity='low', then=3), models.When(severity='info', then=4), default=5)],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('in_scope', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='core.engagement')),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.scanjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('hash_value', models.CharField(blank=True, max_length=500)),
                ('hash_type', models.CharField(blank=True, max_length=50)),
                ('valid', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.host')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.port')),
            ],
        ),
    ]
